version: 2.1

orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 Blog/manage.py test
          name: Test
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: cd Frontend && npm ci
      - run: cd Frontend && CI=true npm run build

workflows:
  test_my_app:
    jobs:
      - build-and-test
      - install-node-example
