version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: cd Frontend && npm ci
      - run: cd Frontend && npm test

workflows:
  test_my_app:
    jobs:
      - install-node-example
